version: "2.2"
services:
  jobmanager:
    image: pyflink-docker:1.15.2
    volumes:
    - ./:/home/pyflink
    ports:
      - "8081:8081"
      - "8888:8888"
    command: jobmanager 
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    image: pyflink-jupyter:1.15.1
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2